spring:
  main:
    web-application-type: none
ringana:
  productsUrl: ${RINGANA_PRODUCTS_URL:https://bla}
  pricesUrl: ${RINGANA_PRICES_URL:https://prices}
  outputFolder: ${RINGANA_OUTPUT_FOLDER:output}